import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.ops as ops

# ==============================================================================
# MODULE 1: Entropy-based Mask Refinement and Box Re-querying (Refine & Requery)
# ==============================================================================

def refine_and_requery_keyframe(initial_prob_mask, image, sam_model, epsilon=0.2):
    """
    Refines an initial probability mask using entropy-based filtering and 
    requeries the SAM model with a generated bounding box to obtain a higher-quality mask.
    
    Args:
        initial_prob_mask (torch.Tensor): Initial mask probabilities of shape [H, W] 
                                          or [1, 1, H, W], with values in [0, 1].
        image (torch.Tensor or Any): The input keyframe image format expected by sam_model.
        sam_model (nn.Module or Callable): The Segment Anything Model that takes 
                                           (image, box) as input.
        epsilon (float): Threshold for the gated confidence mask.
        
    Returns:
        torch.Tensor: The final high-quality reference mask generated by SAM.
    """
    # Ensure mask is [H, W] for calculations
    M = initial_prob_mask.squeeze()
    assert M.ndim == 2, "initial_prob_mask should be 2D after squeezing"
    
    # 1. Entropy Refinement
    # H_ij = - [ M_ij * log2(M_ij + 1e-7) + (1 - M_ij) * log2(1 - M_ij + 1e-7) ]
    # Clamp values to avoid log2(0) beyond 1e-7 and maintain numerical stability
    M_safe = torch.clamp(M, 1e-7, 1.0 - 1e-7)
    H = - (M_safe * torch.log2(M_safe) + (1.0 - M_safe) * torch.log2(1.0 - M_safe))
    
    # Gated Confidence Mask C_ij = 1 if M_ij * (1 - H_ij) > epsilon else 0
    confidence = M * (1.0 - H)
    C = (confidence > epsilon).to(torch.float32)
    
    # 2. Bounding Box Generation
    # Fallback if no confident pixels are found to avoid crash
    if C.sum() == 0:
        fallback_mask = (M > 0.5).to(torch.float32)
        if fallback_mask.sum() == 0:
            return M  # No valid objects found, return initial mask
        else:
            C = fallback_mask
            
    # ops.masks_to_boxes expects mask of shape [N, H, W]
    # It returns boxes in [xmin, ymin, xmax, ymax] format
    boxes = ops.masks_to_boxes(C.unsqueeze(0))  # Shape: [1, 4]
    box = boxes[0]
    
    # Extract coordinates
    xmin, ymin, xmax, ymax = box[0].item(), box[1].item(), box[2].item(), box[3].item()
    
    # Format per user requirement: [ymin, xmin, ymax, xmax]
    # (Note: Most SAM implementations expect [xmin, ymin, xmax, ymax], adapt as needed
    # when calling your specific SAM implementation's forward pass)
    sam_box = [ymin, xmin, ymax, xmax] 
    
    # 3. SAM Re-querying
    # Prompt the SAM model with the extracted bounding box and the key frame image.
    # Depending on the wrapper, it might expect a list or a tensor.
    final_mask = sam_model(image, box=sam_box)
    
    return final_mask


# ==============================================================================
# MODULE 2: Soft Semantic Alignment (SSA) Loss (Reinforce)
# ==============================================================================

class SoftSemanticAlignment(nn.Module):
    def __init__(self, queue_size=128, embedding_dim=256):
        """
        Soft Semantic Alignment (SSA) module to regularize temporal feature 
        propagation during the tracking/training phase.
        
        Args:
            queue_size (int): The number of historical embeddings to keep in the FIFO queue.
            embedding_dim (int): Dimensionality of the feature embeddings.
        """
        super(SoftSemanticAlignment, self).__init__()
        self.queue_size = queue_size
        self.embedding_dim = embedding_dim
        
        # 1. L2-Normalized Embedding Queue
        # We register the queue as a buffer so it is saved in the state_dict but is not 
        # a trainable parameter. Initialize with random values and L2 normalize.
        queue_init = torch.randn(queue_size, embedding_dim)
        queue_init = F.normalize(queue_init, p=2, dim=1)
        self.register_buffer('queue', queue_init)
        
        # Pointer for the FIFO queue to keep track of where to insert next
        self.register_buffer('ptr', torch.zeros(1, dtype=torch.long))

    @torch.no_grad()
    def _dequeue_and_enqueue(self, keys):
        """
        Update the FIFO queue with new keys (historical embeddings).
        
        Args:
            keys (torch.Tensor): New L2-normalized embeddings to add. Shape: [batch_size, embedding_dim]
        """
        batch_size = keys.shape[0]
        ptr = int(self.ptr)
        
        # Handle queue updates depending on batch size
        if ptr + batch_size <= self.queue_size:
            self.queue[ptr:ptr + batch_size] = keys
            ptr = (ptr + batch_size) % self.queue_size
        else:
            # Wrap-around case
            remain = self.queue_size - ptr
            self.queue[ptr:] = keys[:remain]
            self.queue[:batch_size - remain] = keys[remain:]
            ptr = batch_size - remain

        self.ptr[0] = ptr

    def forward(self, current_embeddings, update_queue=True):
        """
        Calculates the SSA loss between current embeddings and the historical queue.
        
        Args:
            current_embeddings (torch.Tensor): Features from the current frame. 
                                               Shape: [batch_size, embedding_dim]
            update_queue (bool): If True, enqueues current embeddings into the historical queue.
            
        Returns:
            torch.Tensor: The computed Loss_SSA scalar.
        """
        # 1. L2-Normalize current embeddings (\hat{h} = h / ||h||_2)
        h_hat = F.normalize(current_embeddings, p=2, dim=1)  # [batch_size, embedding_dim]
        
        # Fetch historical embeddings (\hat{s}) which are already normalized
        # Detach to prevent gradients from flowing back into historical states
        s_hat = self.queue.clone().detach()  # [queue_size, embedding_dim]
        
        # 2. SSA Loss Function
        # Calculate cosine similarity: h_hat * s_hat.T -> [batch_size, queue_size]
        # Represents \hat{s}_i^T * \hat{h}_i for all combinations
        similarity = torch.matmul(h_hat, s_hat.T) 
        
        # Loss_SSA = (1 / q) * sum(1 - \hat{s}_i^T * \hat{h}_i)
        # We average over both the queue size and the batch size
        loss_ssa = (1.0 - similarity).mean()
        
        # 3. Update the historical queue with the new frame embeddings
        if update_queue:
            self._dequeue_and_enqueue(h_hat.detach())
            
        return loss_ssa
